name: "Test run Action"

runs:
  using: 'composite'
  steps:
    - name: Port-forward service
      shell: bash
      run: |
        kubectl get svc atp-itf-executor -n executor
        kubectl describe svc atp-itf-executor -n executor
        echo "🚀 Starting kubectl port-forward in background..."

        kubectl port-forward svc/atp-itf-executor 8080:8080 -n executor > port-forward.log 2>&1 &
        echo $! > port_forward_pid.txt

        for i in {1..10}; do
          if nc -z localhost 8080; then
            echo "✅ Port-forward is working"
            break
          fi
          echo "⏳ Waiting for port-forward..."
          sleep 2
        done

        if ! nc -z localhost 8080; then
          echo "❌ Port-forward did not start in time"
          cat port-forward.log
          exit 1
        fi

    - name: Run Newman
      uses: matt-ball/newman-action@v2.0.0
      with:
        collection: ./qubership-testing-platform-itf-executor/.github/actions/tests/collection.json
        environment: ./qubership-testing-platform-itf-executor/.github/actions/tests/environment.json