openapi: 3.0.1
info:
  title: ITF Executor API
  description: ITF Executor API
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
tags:
  - name: itf-stubs-request-controller
    description: Itf Stubs Request Controller
paths:
  '/trigger/all/active':
    get:
      tags:
        - itf-stubs-request-controller
      summary: getAllActiveTriggers
      operationId: getAllActiveTriggers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TriggerSample'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/trigger/all':
    get:
      tags:
        - itf-stubs-request-controller
      summary: getAllTriggersByProject
      operationId: getAllTriggersByProject
      parameters:
        - name: projectUuid
          in: query
          description: projectUuid
          required: true
          schema:
            type: javaUUID
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TriggerSample'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/trigger/all/reactivate':
    get:
      tags:
        - itf-stubs-request-controller
      summary: getAllActiveAndErrorTriggersByProject
      operationId: getAllActiveAndErrorTriggersByProject
      parameters:
        - name: projectUuid
          in: query
          description: projectUuid
          required: true
          schema:
            type: javaUUID
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TriggerSample'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/trigger/environment/folder/{id}':
    get:
      tags:
        - itf-stubs-request-controller
      summary: getTriggersByEnvFolder
      operationId: getTriggersByEnvFolder
      parameters:
        - name: id
          in: path
          description: envFolderId
          required: true
          schema:
            type: biginteger
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EnvironmentSample'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/trigger/environmentId/{id}':
    get:
      tags:
        - itf-stubs-request-controller
      summary: getTriggersByEnvironment
      operationId: getTriggersByEnvironment
      parameters:
        - name: id
          in: path
          description: environmentId
          required: true
          schema:
            type: biginteger
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentSample'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/trigger/{id}':
    get:
      tags:
        - itf-stubs-request-controller
      summary: getTriggerById
      operationId: getTriggerById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: biginteger
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TriggerSample'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/trigger':
    patch:
      tags:
        - itf-stubs-request-controller
      summary: updateTriggerStatus
      operationId: updateTriggerStatus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UIUpdateTriggerStatus'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    TriggerSample:
      title: TriggerSample
      type: object
      properties:
        triggerId:
          type: string
        triggerName:
          type: string
        triggerTypeName:
          type: string
        transportName:
          type: string
        serverName:
          type: string
        triggerState:
          type: string
          enum:
            - Active
            - Inactive
            - Error
            - Starting
            - Shutting down
            - Active (Not all)
            - Active (Errors)
            - Empty
        transportType:
          type: string
          enum:
            - CLI_INBOUND
            - FILE_INBOUND
            - HTTP_INBOUND
            - HTTP2_INBOUND
            - JMS_INBOUND
            - KAFKA_INBOUND
            - REST_INBOUND
            - SNMP_INBOUND
            - SOAP_OVER_HTTP_INBOUND
            - SMPP_INBOUND
        triggerProperties:
          type: string
          additionalProperties:
            type: object
        projectUuid:
          type: string
          format: uuid
        projectId:
          type: biginteger
    EnvironmentSample:
      title: EnvironmentSample
      type: object
      properties:
        envId:
          type: biginteger
        turnedOn:
          type: boolean
        triggerSamples:
          type: array
          items:
            $ref: '#/components/schemas/TriggerSample'
    UIUpdateTriggerStatus:
      title: UIUpdateTriggerStatus
      type: object
      properties:
        id:
          type: biginteger
        status:
          type: string
        description:
          type: string
    Result:
      title: Result
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: string
          additionalProperties:
            type: string