---
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
spec:
  ports:
{{- $ports := .Values.defaultPorts -}}
{{- $additionalPorts := .Values.additionalPorts -}}
{{- if $additionalPorts }}
  {{- $ports := merge $ports $additionalPorts }}
{{- end }}
{{- range $key, $value := $ports }}
  - port: {{ $value.port | int }}
    name: {{ $key }}
{{- end }}
  selector:
    name: '{{ .Values.SERVICE_NAME }}'
  type: NodePort
